// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwzldhsN9f9RCl8TCAginH_5mQAjZvPkY',
    appId: '1:770938877046:web:1cd95c36998b0e5eca5b57',
    messagingSenderId: '770938877046',
    projectId: 'ticket-kini',
    authDomain: 'ticket-kini.firebaseapp.com',
    storageBucket: 'ticket-kini.firebasestorage.app',
    measurementId: 'G-05YRR6SMMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYRZjI6GGz3Z_i3t0W_7IQej53fgw_taw',
    appId: '1:770938877046:android:ce2bb173ac1a81b8ca5b57',
    messagingSenderId: '770938877046',
    projectId: 'ticket-kini',
    storageBucket: 'ticket-kini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiY3v3Rgw7gUlBNnnnrGPSwcmVbkUB8lI',
    appId: '1:770938877046:ios:818d19a9434496d4ca5b57',
    messagingSenderId: '770938877046',
    projectId: 'ticket-kini',
    storageBucket: 'ticket-kini.firebasestorage.app',
    iosBundleId: 'com.example.ticketKini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiY3v3Rgw7gUlBNnnnrGPSwcmVbkUB8lI',
    appId: '1:770938877046:ios:818d19a9434496d4ca5b57',
    messagingSenderId: '770938877046',
    projectId: 'ticket-kini',
    storageBucket: 'ticket-kini.firebasestorage.app',
    iosBundleId: 'com.example.ticketKini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwzldhsN9f9RCl8TCAginH_5mQAjZvPkY',
    appId: '1:770938877046:web:323e349b8e786bfdca5b57',
    messagingSenderId: '770938877046',
    projectId: 'ticket-kini',
    authDomain: 'ticket-kini.firebaseapp.com',
    storageBucket: 'ticket-kini.firebasestorage.app',
    measurementId: 'G-GTJ5F56MJW',
  );
}
